{
 "title": "PFsense Graylog",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "DNS queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 7, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "destination-port:53",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Size of blocked packets (MB)",
   "type": "timeseries",
   "description": "Data size that was blocked",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source-address",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data-length", "id": "1", "settings": { "script": "_value/1000" }, "type": "sum" }
     ],
     "query": "action:block",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Clients with most new connection counts",
   "type": "timeseries",
   "description": "Shows the clients that initiate the most amount of new connections",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source-address",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "real_timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action:pass AND direction:in",
     "timeField": "real_timestamp"
    }
   ]
  },
  { "title": "Data Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  { "title": "Noise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "(IPv4, INTERNAL) Top 10 noisiest clients",
   "type": "piechart",
   "description": "The top ten noisiest IPv4 clients with a firewall direction of in.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source-address",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action:pass AND direction:in AND ip-version:4",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "(IPv6, INTERNAL) Top 10 noisiest clients",
   "type": "piechart",
   "description": "The top ten noisiest IPv6 clients with a firewall direction of in.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source-address",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action:pass AND direction:in AND ip-version:6",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "(Internal) Top 10 noisiest clients",
   "type": "piechart",
   "description": "The top ten noisiest clients with a firewall direction of in.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source-address",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action:pass AND direction:in",
     "timeField": "real_timestamp"
    }
   ]
  },
  { "title": "BLOCKED Ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "(IPv4) BLOCKED destination ports",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "settings": { "size": "500" },
       "type": "raw_data"
      }
     ],
     "query": "ip-version:4 AND action:block",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "(IPv6) BLOCKED destination ports",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "ip-version:6 AND action:block",
     "timeField": "real_timestamp"
    }
   ]
  },
  {
   "title": "Firewall Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Firewall Blocks ",
     "type": "stat",
     "description": "This is the number of times our firewall has blocked bogus or unwanted traffic from entering our network.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "action:block",
       "timeField": "real_timestamp"
      }
     ]
    },
    {
     "title": "Number of Firewall Passes",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "real_timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "action:pass",
       "timeField": "real_timestamp"
      }
     ]
    },
    {
     "title": "Top 10 Blocked Clients",
     "type": "piechart",
     "description": "The top ten most blocked clients",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "source-address",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "action:block",
       "timeField": "real_timestamp"
      }
     ]
    }
   ]
  }
 ]
}